import "./globals.css";
import { ReduxProvider } from "@/store/reduxProvider";
import GlobalWrapper from "@/components/foundation/GlobalWrapper";

export const metadata = {
  title: "Khana-kazana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex flex-col min-h-screen antialiased">
        <ReduxProvider>
          <GlobalWrapper>{children}</GlobalWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
